### ISSUE TITLE
Chart metadata (Chart.yaml) missing but exists in current directory

### ISSUE THREAD

**Issue by edisinovcic** [J12934/helm-gh-pages-action#4]
Charts dir content
ls -I ".*"
Chart.yaml
deploy.sh
templates
values.yaml
Resolving helm chart dependency in directory templates
helm dependency update
Error: chart metadata (Chart.yaml) missing
##[error]The process 'helm' failed with exit code 1
##[error]Node run failed with exit code 1

**Comment by J12934** [comment]
Hi 👋
Is the repo you are trying to use this on OpenSource by any chance? Could take a deeper look then.
Otherwise can you compare it to the helm chart here: https://github.com/iteratec/multi-juicer/tree/master/helm/multi-juicer, to see if your chart is missing something?

**Comment by edisinovcic** [comment]
I'm probably missing something, here is an action:
https://github.com/blockchain-it-hr/ink-remix-plugin/runs/390995233

**Comment by edisinovcic** [comment]
I've managed to fix it, everything works, tnx for the help :)
